### ISSUE TITLE
Currently playing component

### ISSUE THREAD

**Issue by shibeknight** [double-dashers/one-for-all#22]
As a developer, I would like my user view to have a  simple "currently playing" component, in order to visualize quickly the current games that the user is following and work on improvements.

**Acceptance criteria**

-The component accepts props and is independent
-The component is imported in the user view
-The component has mock data to visualize how the UI will be and is open for future improvements

**Comment by avelinoschz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Currently playing card component](https://trello.com/c/OEbkHxig/33-currently-playing-card-component)
