### ISSUE TITLE
Activity feed component

### ISSUE THREAD

**Issue by shibeknight** [double-dashers/one-for-all#24]
As a developer, I would like to create an activity feed component, in order to visualize a feed of items in the user's profile view that can show relevant data.

**Acceptance criteria**

-The component is responsive and independent
-The component is imported in the user view
-The component holds mock data to showcase the style of the feed, takes props from the parent and is open for future enhancements

**Comment by avelinoschz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Activity component](https://trello.com/c/BeHgpsRk/35-activity-component)
