### ISSUE TITLE
React style guide linter

### ISSUE THREAD

**Issue by avelinoschz** [double-dashers/one-for-all#6]
As a developer, I would like the code to format automatically following some style guide, in order to have a consistent code styling.

Minimum requirements:
*Choose a code style guide.
*Add a linter to the project.
*The linter automatically formats the code.

**Comment by shibeknight** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Airbnb linter for React App](https://trello.com/c/oTePgUIj/5-airbnb-linter-for-react-app)
